package com.loc.electricity.domain.shared;

public enum AuditAction {
    LOGIN, LOGOUT,
    CREATE_CUSTOMER, UPDATE_CUSTOMER, DELETE_CUSTOMER,
    CREATE_PERIOD, CALCULATE_PERIOD, APPROVE_PERIOD, REVERT_PERIOD, CLOSE_PERIOD,
    CREATE_EVN_INVOICE, UPDATE_EVN_INVOICE, DELETE_EVN_INVOICE,
    UPDATE_METER_READING,
    CREATE_PAYMENT, ASSIGN_PAYMENT,
    UPDATE_SETTING
}
