#!/usr/bin/env python3
"""
generate_v11_cleanup.py

Generates V11__cleanup_demo_and_fix_v10.sql which:
  1. Deletes demo seed data (KH001-KH010, periods 2025-02/03/04 and related rows)
  2. Updates KH008 to the real customer name
  3. Re-inserts the 3 periods that were IGNORED by V10 (because demo data existed)

Usage:
    python3 scripts/generate_v11_cleanup.py
"""

import os
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

V10_SQL_PATH = os.path.join(
    BASE_DIR, "src", "main", "resources", "db", "migration",
    "V10__seed_historical_data.sql"
)

OUTPUT_PATH = os.path.join(
    BASE_DIR, "src", "main", "resources", "db", "migration",
    "V11__cleanup_demo_and_fix_v10.sql"
)

# Demo customer codes that must be removed
DEMO_CODES_DELETE   = ['KH001', 'KH002', 'KH003', 'KH004', 'KH005',
                        'KH006', 'KH007', 'KH009', 'KH010']
# KH008 exists in real data — update name instead of delete
KH008_REAL_NAME     = 'Lâm Thanh Tùng'

# Periods that demo data occupied; V10 INSERTs were IGNORED for these
MISSED_PERIODS      = ['2025-02', 'Kỳ tháng 02/2025',
                       '2025-03', 'Kỳ tháng 03/2025',
                       '2025-04', 'Kỳ tháng 04/2025']
DEMO_PERIOD_CODES   = ['2025-02', '2025-03', '2025-04']

# ─────────────────────────────────────────────────────────────
# Extract the rows for the 3 missed periods from V10
# ─────────────────────────────────────────────────────────────

print(f"Reading V10 SQL: {V10_SQL_PATH}")
with open(V10_SQL_PATH, encoding='utf-8') as f:
    v10_lines = f.readlines()

def rows_for_periods(lines, prefix, period_codes):
    """Filter SQL lines that match prefix AND contain one of the period codes."""
    targets = [f"'{p}'" for p in period_codes]
    return [
        l.rstrip()
        for l in lines
        if l.strip().startswith(prefix) and any(t in l for t in targets)
    ]

bp_rows   = rows_for_periods(v10_lines, 'INSERT IGNORE INTO billing_period', DEMO_PERIOD_CODES)
evn_rows  = rows_for_periods(v10_lines, 'INSERT INTO evn_invoice',           DEMO_PERIOD_CODES)
mr_rows   = rows_for_periods(v10_lines, 'INSERT IGNORE INTO meter_reading',  DEMO_PERIOD_CODES)
bill_rows = rows_for_periods(v10_lines, 'INSERT IGNORE INTO bill ',          DEMO_PERIOD_CODES)

print(f"  billing_period rows to re-insert: {len(bp_rows)}")
print(f"  evn_invoice rows:                 {len(evn_rows)}")
print(f"  meter_reading rows:               {len(mr_rows)}")
print(f"  bill rows:                        {len(bill_rows)}")

# ─────────────────────────────────────────────────────────────
# Build SQL
# ─────────────────────────────────────────────────────────────

demo_codes_sql  = ', '.join(f"'{c}'" for c in DEMO_CODES_DELETE)
period_codes_sql = ', '.join(f"'{p}'" for p in DEMO_PERIOD_CODES)

lines = []
lines += [
    "-- " + "═" * 62,
    "-- V11__cleanup_demo_and_fix_v10.sql",
    "-- Generated by scripts/generate_v11_cleanup.py",
    f"-- Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    "--",
    "-- Purpose:",
    "--   1. Remove demo seed data (KH001–KH010, periods 2025-02/03/04)",
    "--   2. Correct KH008 customer name to real data",
    "--   3. Re-insert real data for 2025-02, 2025-03, 2025-04",
    "--      (these were IGNORED by V10 because demo data occupied those codes)",
    "-- " + "═" * 62,
    "",
    "SET NAMES utf8mb4;",
    "SET FOREIGN_KEY_CHECKS = 0;",
    "",
]

# ── STEP 1: Delete demo period data in FK order ──────────────
lines += [
    "-- " + "─" * 62,
    "-- STEP 1: Delete demo period data (2025-02, 2025-03, 2025-04)",
    "-- " + "─" * 62,
    "",
    "-- 1a. Payments linked to demo period bills",
    f"DELETE FROM payment WHERE bill_id IN (",
    f"    SELECT id FROM bill WHERE period_id IN (",
    f"        SELECT id FROM billing_period WHERE code IN ({period_codes_sql})",
    f"    )",
    f");",
    "",
    "-- 1b. SMS logs linked to demo period bills",
    f"DELETE FROM sms_log WHERE bill_id IN (",
    f"    SELECT id FROM bill WHERE period_id IN (",
    f"        SELECT id FROM billing_period WHERE code IN ({period_codes_sql})",
    f"    )",
    f");",
    "",
    "-- 1c. Bills for demo periods",
    f"DELETE FROM bill WHERE period_id IN (",
    f"    SELECT id FROM billing_period WHERE code IN ({period_codes_sql})",
    f");",
    "",
    "-- 1d. Meter readings for demo periods",
    f"DELETE FROM meter_reading WHERE period_id IN (",
    f"    SELECT id FROM billing_period WHERE code IN ({period_codes_sql})",
    f");",
    "",
    "-- 1e. EVN invoices for demo periods",
    f"DELETE FROM evn_invoice WHERE period_id IN (",
    f"    SELECT id FROM billing_period WHERE code IN ({period_codes_sql})",
    f");",
    "",
    "-- 1f. Demo billing periods themselves",
    f"DELETE FROM billing_period WHERE code IN ({period_codes_sql});",
    "",
]

# ── STEP 2: Delete demo-only customers ───────────────────────
lines += [
    "-- " + "─" * 62,
    "-- STEP 2: Delete demo-only customers (KH001-KH007, KH009-KH010)",
    "-- Note: KH008 is kept — it is a real customer (name updated in step 3)",
    "-- " + "─" * 62,
    "",
    "-- 2a. Any remaining bills for demo customers (safety net)",
    f"DELETE FROM bill WHERE customer_id IN (",
    f"    SELECT id FROM customer WHERE code IN ({demo_codes_sql})",
    f");",
    "",
    "-- 2b. Any remaining meter readings for demo customers",
    f"DELETE FROM meter_reading WHERE customer_id IN (",
    f"    SELECT id FROM customer WHERE code IN ({demo_codes_sql})",
    f");",
    "",
    "-- 2c. SMS logs for demo customers",
    f"DELETE FROM sms_log WHERE customer_id IN (",
    f"    SELECT id FROM customer WHERE code IN ({demo_codes_sql})",
    f");",
    "",
    "-- 2d. Delete demo customers",
    f"DELETE FROM customer WHERE code IN ({demo_codes_sql});",
    "",
]

# ── STEP 3: Fix KH008 ─────────────────────────────────────────
lines += [
    "-- " + "─" * 62,
    "-- STEP 3: Update KH008 to real customer info",
    "-- Demo name was 'Ngô Thị Hoa'; real name is 'Lâm Thanh Tùng'",
    "-- " + "─" * 62,
    "",
    f"UPDATE customer",
    f"SET    full_name    = '{KH008_REAL_NAME}',",
    f"       phone        = NULL,",
    f"       zalo_phone   = NULL,",
    f"       meter_serial = NULL,",
    f"       updated_at   = NOW()",
    f"WHERE  code = 'KH008';",
    "",
]

# ── STEP 4: Re-insert 3 periods ───────────────────────────────
lines += [
    "-- " + "─" * 62,
    f"-- STEP 4: Re-insert billing_period for 2025-02, 2025-03, 2025-04",
    "-- " + "─" * 62,
    "",
]
lines += bp_rows
lines.append("")

# ── STEP 5: Re-insert EVN invoices ────────────────────────────
lines += [
    "-- " + "─" * 62,
    f"-- STEP 5: Re-insert EVN invoices ({len(evn_rows)} rows)",
    "-- " + "─" * 62,
    "",
]
lines += evn_rows
lines.append("")

# ── STEP 6: Re-insert meter readings ─────────────────────────
lines += [
    "-- " + "─" * 62,
    f"-- STEP 6: Re-insert meter readings ({len(mr_rows)} rows)",
    "-- consumption is STORED GENERATED — not inserted",
    "-- " + "─" * 62,
    "",
]
lines += mr_rows
lines.append("")

# ── STEP 7: Re-insert bills ───────────────────────────────────
lines += [
    "-- " + "─" * 62,
    f"-- STEP 7: Re-insert bills ({len(bill_rows)} rows)",
    "-- " + "─" * 62,
    "",
]
lines += bill_rows
lines.append("")

lines += ["SET FOREIGN_KEY_CHECKS = 1;", ""]

# ─────────────────────────────────────────────────────────────
# Write output
# ─────────────────────────────────────────────────────────────

content = "\n".join(lines)
with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print()
print("=" * 55)
print("  V11 Summary")
print("=" * 55)
print(f"  Demo customers deleted:  {len(DEMO_CODES_DELETE)}  ({', '.join(DEMO_CODES_DELETE[:4])}...)")
print(f"  KH008 name updated to:   {KH008_REAL_NAME}")
print(f"  Demo periods cleared:    {', '.join(DEMO_PERIOD_CODES)}")
print(f"  Periods re-inserted:     {len(bp_rows)}")
print(f"  Meter readings re-ins:   {len(mr_rows)}")
print(f"  Bills re-inserted:       {len(bill_rows)}")
print()
print(f"  Output: {OUTPUT_PATH}")
print(f"  File size: {len(content.encode('utf-8')):,} bytes")
print("=" * 55)
